### ISSUE TITLE
建议增加app关闭后的重入

### ISSUE THREAD

**Issue by visuddhinanda** [iapt-platform/wikipali-app#3]
问题描述：
切换到其他app后。再返回。app有可能被kill重新启动。启动后为初始状态。需要手工找到原来的阅读位置。

希望的效果：
重新启动后。自动返回原来的阅读经文的位置或字典查询的位置。

**Comment by briancd2023** [comment]
您好，尊者：
在github.com搜索到另一个巴利三藏的项目：
https://github.com/bksubhuti
https://github.com/bksubhuti/Tipitaka-Pali-Projector/releases
https://github.com/bksubhuti/tipitaka-pali-reader/releases
请您参考。

**Comment by ariyamaggika** [comment]
v1.1.0版本 已实现

**Comment by ariyamaggika** [comment]
> 您好，尊者： 在github.com搜索到另一个巴利三藏的项目： [@bksubhuti](https://github.com/bksubhuti) [bksubhuti/Tipitaka-Pali-Projector/releases](https://github.com/bksubhuti/Tipitaka-Pali-Projector/releases) [bksubhuti/tipitaka-pali-reader/releases](https://github.com/bksubhuti/tipitaka-pali-reader/releases) 请您参考。

收到，萨度！
